version: '3.3'

services:
  swordbattleio:
    image: swordbattleio
    build: .
    ports:
      - 3300:3300
    environment:
      - PORT=3300
    networks:
      - caddy

  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-config:/config
      - ./caddy-data:/data
    networks:
      - caddy

networks:
  caddy:

